### ISSUE TITLE
Deposit ETH Into Validator Registration Contract via CLI Flag Upon System Start

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/beacon-chain#15]
Hi all,

To run a beacon node, we can specify whether or not the user wants to deposit ETH into the Validator Registration Contract upon the system starting. Once this occurs, a tx would be broadcast to the main chain via RPC and the beacon node would listen for it the logs in the contract and begin the validator queue registration process. 

A PR for this issue would implement the functionality above and keep an active validator set as part of the beacon chain node.

**Comment by terenc3t** [comment]
To add more color to this, when user clicks a button that says "deposit, the client should generates the default verification code, sets the withdrawal address to the same as the address client sent from unless specified otherwise and publish the transaction automatically.

Speaking of verification code, the default should just be elliptic curve verification (ECRECOVER). Quantum resistant hash ladder sigs is another one that has been implemented. Here are some that could implement: multisig M of N ECRECOVER, threshold signature (e.g. BLS) and keys that can authorize other keys.

**Comment by prestonvanloon** [comment]
Blocked by #17

**Comment by rauljordan** [comment]
The reason why I am closing this is because the Beacon Chain will **NOT** need write access to the main chain. The only pieces of functionality related to main chain interaction the beacon chain contains are:

- Fetching the latest block hash
- Fetching the latest block number
- Reading the logs from the Validator Registration Contract to check for registered validators

The deposit of 32ETH into the contract should be done external to the beacon chain repo, and it should not be a baked in piece of functionality.
