### ISSUE TITLE
Research and Integrate CI for Beacon-chain Repo

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/beacon-chain#4]
As discussed earlier, Travis in our [client](https://github.com/prysmaticlabs/geth-sharding/tree/master/sharding) repo hasn't been working well. Flaky time outs and long dependent test times have been frustrating. Let's explore a better solution, perhaps Bazel? Opening up this issue to continue the discussions.

**Comment by prestonvanloon** [comment]
I would like to see this using Bazel with a persistent remote cache when running Travis.

The problem is that go-ethereum is not Bazel friendly at the moment. Their C wrapper [secp256k1](https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1) uses relative imports which breaks discovery for bazel. 

We would need to break dependence on go-ethereum as is or fix the above problem to support Bazel build.
